name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            target: Win32
          - name: macOS
            os: macos-latest
            target: Mac
          - name: iOS
            os: macos-latest
            target: iOS
          - name: Android32
            os: ubuntu-latest
            target: Android32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ccache
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-geode-${{ matrix.config.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-geode-${{ matrix.config.target }}-

      - name: Setup Geode SDK
        uses: geode-sdk/setup@main
        with:
          cli: 'latest'
          sdk: 'latest'

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          android-ndk-version: 'r26b'
          combine: false

  package:
    name: Package Builds
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Merge Platform Builds
        uses: geode-sdk/build-geode-mod/combine@main
